"""empty message

Revision ID: 16e9c4460b9b
Revises: 0e15e66a1bed
Create Date: 2021-11-02 18:19:19.886302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e9c4460b9b'
down_revision = '0e15e66a1bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('time_dependency', sa.Boolean(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navigation_mode', sa.Enum('LINEAR', 'NON_LINEAR', name='navigationmode'), nullable=True),
    sa.Column('submission_mode', sa.Enum('INDIVIDUAL', 'SIMULTANEOUS', name='submissionmode'), nullable=True),
    sa.Column('time_dependency', sa.Boolean(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='grade'), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('time_dependency', sa.Boolean(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('interaction', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_dependency', sa.Boolean(), nullable=True),
    sa.Column('correct_answer', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('max_choices', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('subject_student_subject_id_fkey', 'subject_student', type_='foreignkey')
    op.create_foreign_key(None, 'subject_student', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint('subject_teacher_subject_id_fkey', 'subject_teacher', type_='foreignkey')
    op.create_foreign_key(None, 'subject_teacher', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_teacher', type_='foreignkey')
    op.create_foreign_key('subject_teacher_subject_id_fkey', 'subject_teacher', 'students', ['subject_id'], ['id'])
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.create_foreign_key('subject_student_subject_id_fkey', 'subject_student', 'students', ['subject_id'], ['id'])
    op.drop_table('options')
    op.drop_table('items')
    op.drop_table('sections')
    op.drop_table('test_result')
    op.drop_table('parts')
    op.drop_table('tests')
    op.drop_table('subjects')
    # ### end Alembic commands ###
