"""empty message

Revision ID: 2027df32b685
Revises: ccfef0bb5942
Create Date: 2021-10-27 11:13:08.051352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2027df32b685'
down_revision = 'ccfef0bb5942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('interaction', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('response', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('max_choices', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'max_choices')
    op.drop_column('items', 'answer')
    op.drop_column('items', 'response')
    op.drop_column('items', 'interaction')
    op.drop_table('options')
    # ### end Alembic commands ###
