"""empty message

Revision ID: 3edd8d2a0da0
Revises: 852e68a8f68b
Create Date: 2021-11-03 13:19:14.163469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edd8d2a0da0'
down_revision = '852e68a8f68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'correct_answer')
    op.add_column('options', sa.Column('correct_answer', sa.Boolean(), nullable=True))
    op.add_column('options', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'checked')
    op.drop_column('options', 'correct_answer')
    op.add_column('items', sa.Column('correct_answer', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
