"""empty message

Revision ID: 5b553214613c
Revises: 8a1a2a4c121c
Create Date: 2021-12-28 15:35:51.941026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b553214613c'
down_revision = '8a1a2a4c121c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_kspace',
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('kspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kspace_id'], ['kspaces.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], )
    )
    op.drop_constraint('kspaces_problem_fkey', 'kspaces', type_='foreignkey')
    op.drop_column('kspaces', 'problem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kspaces', sa.Column('problem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('kspaces_problem_fkey', 'kspaces', 'sections', ['problem'], ['id'])
    op.drop_table('section_kspace')
    # ### end Alembic commands ###
