"""empty message

Revision ID: 7817e9643b49
Revises: 7bc99e9f2917
Create Date: 2021-10-26 20:51:25.728333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7817e9643b49'
down_revision = '7bc99e9f2917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navigation_mode', sa.Enum('LINEAR', 'NON_LINEAR', name='navigation_mode'), nullable=True),
    sa.Column('submission_mode', sa.Enum('INDIVIDUAL', 'SIMULTANEOUS', name='submission_mode'), nullable=True),
    sa.Column('time_dependancy', sa.Boolean(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    # ### end Alembic commands ###
