"""empty message

Revision ID: 7bc99e9f2917
Revises: 943b84d27ed2
Create Date: 2021-10-26 20:46:36.762773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc99e9f2917'
down_revision = '943b84d27ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'subject_id')
    # ### end Alembic commands ###
