"""empty message

Revision ID: 852e68a8f68b
Revises: 
Create Date: 2021-11-03 07:47:04.026997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852e68a8f68b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='grade'), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('items', 'response')
    op.drop_column('items', 'time_dependancy')
    op.drop_column('items', 'answer')
    op.add_column('parts', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('parts', 'time_dependancy')
    op.drop_column('sections', 'time_dependancy')
    op.add_column('tests', sa.Column('time_dependency', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    op.drop_column('tests', 'time_dependancy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tests', 'time_limit_seconds')
    op.drop_column('tests', 'time_dependency')
    op.add_column('sections', sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('parts', 'title')
    op.add_column('items', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('test_result')
    # ### end Alembic commands ###
