"""empty message

Revision ID: 8a1a2a4c121c
Revises: 774cc3023880
Create Date: 2021-12-28 14:50:48.850292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1a2a4c121c'
down_revision = '774cc3023880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problems_related_source_fkey', 'problems_related', type_='foreignkey')
    op.drop_constraint('problems_related_target_fkey', 'problems_related', type_='foreignkey')
    op.create_foreign_key(None, 'problems_related', 'kspaces', ['source'], ['id'])
    op.create_foreign_key(None, 'problems_related', 'kspaces', ['target'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems_related', type_='foreignkey')
    op.drop_constraint(None, 'problems_related', type_='foreignkey')
    op.create_foreign_key('problems_related_target_fkey', 'problems_related', 'sections', ['target'], ['id'])
    op.create_foreign_key('problems_related_source_fkey', 'problems_related', 'sections', ['source'], ['id'])
    # ### end Alembic commands ###
