"""empty message

Revision ID: 8cac815a455b
Revises: 15b5bd1de436
Create Date: 2021-11-02 21:52:24.494976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cac815a455b'
down_revision = '15b5bd1de436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'time_dependency')
    op.drop_column('parts', 'time_dependency')
    op.drop_column('sections', 'time_dependency')
    op.add_column('tests', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'time_limit_seconds')
    op.add_column('sections', sa.Column('time_dependency', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('parts', sa.Column('time_dependency', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('time_dependency', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
