"""empty message

Revision ID: 943b84d27ed2
Revises: 1cae0049d480
Create Date: 2021-10-26 20:45:00.144380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943b84d27ed2'
down_revision = '1cae0049d480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('time_dependancy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_student',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['students.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_student')
    op.drop_table('tests')
    # ### end Alembic commands ###
