"""empty message

Revision ID: 9fa0729592d4
Revises: 0a63107102e0
Create Date: 2021-11-09 12:38:40.122370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fa0729592d4'
down_revision = '0a63107102e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_result')
    op.drop_column('items', 'interaction')
    op.drop_column('options', 'checked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('checked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('interaction', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('test_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('points', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grade', postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', name='grade'), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='test_result_student_id_fkey'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='test_result_test_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_result_pkey')
    )
    op.drop_table('option_result')
    # ### end Alembic commands ###
