"""empty message

Revision ID: b7a9d65331db
Revises: cd94f4067ba1
Create Date: 2021-12-28 14:32:32.884322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7a9d65331db'
down_revision = 'cd94f4067ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems_related')
    op.drop_table('kspaces')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kspaces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domen_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('problem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iita_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domen_id'], ['parts.id'], name='kspaces_domen_id_fkey'),
    sa.ForeignKeyConstraint(['problem'], ['sections.id'], name='kspaces_problem_fkey'),
    sa.PrimaryKeyConstraint('id', name='kspaces_pkey')
    )
    op.create_table('problems_related',
    sa.Column('source', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source'], ['sections.id'], name='problems_related_source_fkey'),
    sa.ForeignKeyConstraint(['target'], ['sections.id'], name='problems_related_target_fkey')
    )
    # ### end Alembic commands ###
