"""initial

Revision ID: df7442168f5d
Revises: 2027df32b685
Create Date: 2021-11-02 11:25:39.581288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df7442168f5d'
down_revision = '2027df32b685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('parts')
    op.drop_table('subjects')
    op.drop_table('tests')
    op.drop_table('options')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interaction', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_choices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='items_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='options_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='options_pkey')
    )
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tests_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='tests_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('subjects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('parts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('parts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('navigation_mode', postgresql.ENUM('LINEAR', 'NON_LINEAR', name='navigation_mode'), autoincrement=False, nullable=True),
    sa.Column('submission_mode', postgresql.ENUM('INDIVIDUAL', 'SIMULTANEOUS', name='submission_mode'), autoincrement=False, nullable=True),
    sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='parts_test_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_dependancy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name='sections_part_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sections_pkey')
    )
    # ### end Alembic commands ###
